Metrics/ModuleLength:
  Enabled: false
Metrics/ClassLength:
  Enabled: false
Metrics/LineLength:
  Enabled: false
Style/NumericPredicate:
  Enabled: false
Style/DoubleNegation:
  Enabled: false
Style/Documentation:
  Enabled: false
Lint/EmptyWhen:
  Enabled: false
Style/ParallelAssignment:
  Enabled: false
Style/ClassVars:
  Enabled: false
Naming/AccessorMethodName:
  Enabled: false
Style/AndOr:
  Enabled: false
Style/FrozenStringLiteralComment:
  Enabled: false
Lint/UnderscorePrefixedVariableName:
  Enabled: false
Metrics/BlockLength:
  Enabled: false
Style/BlockDelimiters:
  Enabled: false
Lint/AmbiguousBlockAssociation:
  Enabled: false
Style/MethodCallWithoutArgsParentheses:
  Enabled: false
Layout/TrailingWhitespace:
  Enabled: false
Style/ClassAndModuleChildren:
  Enabled: false
Naming/PredicateName:
  Enabled: false
Style/FormatStringToken:
  Enabled: false
Style/RescueModifier:
  Enabled: false
Metrics/BlockNesting:
  Enabled: false

# Temporary disable method size metrics
Metrics/AbcSize:
  Enabled: false
Metrics/MethodLength:
  Enabled: false


AllCops:
  Exclude:
    - 'bin/*'
    - 'vendor/**/*'
    - 'db/schema.rb'
