- [Gear, cog, data-icon: fa-cog]
- [Globe, globe, data-icon: fa-globe]
- [Adjust, adjust, data-icon: fa-adjust]
- [Camera, camera, data-icon: fa-camera]
- [Glass, wine-glass, data-icon: fa-wine-glass]
- [Music, music, data-icon: fa-music]
- [Heart, heart, data-icon: fa-heart]
- [Star, star, data-icon: fa-star]
- [Film, film, data-icon: fa-film]
- [Signal, signal, data-icon: fa-signal]
- [Home, home, data-icon: fa-home]
- [Automobile, car, data-icon: fa-car]
- [Clock, clock, data-icon: fa-clock]
- [Road, road, data-icon: fa-road]
- [Inbox, inbox, data-icon: fa-inbox]
- [Lock, lock, data-icon: fa-lock]
- [Flag, flag, data-icon: fa-flag]
- [Barcode, barcode, data-icon: fa-barcode]
- [Book, book, data-icon: fa-book]
- [Building, building, data-icon: fa-building]
- [Video Camera, video, data-icon: fa-video]
- [Photo, camera, data-icon: fa-camera]
- [Headphones, headphones, data-icon: fa-headphones]
- [Gift, gift, data-icon: fa-gift]
- [Leaf, leaf, data-icon: fa-leaf]
- [Fire, fire, data-icon: fa-fire]
- [Eye, eye, data-icon: fa-eye]
- [Language, language, data-icon: fa-language]
- [Key, key, data-icon: fa-key]
- [Paw, paw, data-icon: fa-paw]
- [Tags, tags, data-icon: fa-tags]
- [Dashboard, tachometer-alt, data-icon: fa-tachometer-alt]
- [Camera Retro, camera-retro, data-icon: fa-camera-retro]
- [Plane, plane, data-icon: fa-plane]
- [Calendar, calendar, data-icon: fa-calendar]
- [Bullhorn, bullhorn, data-icon: fa-bullhorn]
- [Gears, cogs, data-icon: fa-cogs]
- [Bell, bell, data-icon: fa-bell]
- [Gavel, gavel, data-icon: fa-gavel]
- [Bank, piggy-bank, data-icon: fa-piggy-bank]
- [Coffee, coffee, data-icon: fa-coffee]
- [Cutlery, utensils, data-icon: fa-utensils]
- [Table, table, data-icon: fa-table]
- [Magic, magic, data-icon: fa-magic]
- [Truck, truck, data-icon: fa-truck]
- [Pencil, pencil-alt, data-icon: fa-pencil-alt]
- [Cloud, cloud, data-icon: fa-cloud]
- [Scissors, cut, data-icon: fa-cut]
